In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

path = 'ncaam-march-mania-2021/MDataFiles_Stage1/'

In [2]:
df = pd.read_csv(path+'MRegularSeasonCompactResults.csv')

In [3]:
pomeroy = pd.read_csv('Pomeroy.csv')

In [4]:
df_features_season = df[df['Season']>2001]

In [5]:
df_features_season = pd.merge(
    df_features_season,
    pomeroy,
    how='left',
    left_on=['Season', 'WTeamID'],
    right_on=['Season', 'TeamID']
).rename(columns={
    'Rank':'RankW',
    'AdjEM':'AdjEMW',
    'AdjO':'AdjOW',
    'AdjD':'AdjDW',
    'Luck':'LuckW',
}).drop('TeamID',axis=1)

In [6]:
df_features_season

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,RankW,AdjEMW,AdjOW,AdjDW,LuckW
0,2002,10,1112,71,1268,67,N,0,13.0,20.54,119.3,98.8,0.079
1,2002,10,1196,72,1396,64,N,0,7.0,24.72,115.1,90.4,-0.073
2,2002,11,1112,75,1196,71,N,0,13.0,20.54,119.3,98.8,0.079
3,2002,11,1268,82,1396,74,N,0,3.0,29.25,119.2,89.9,0.025
4,2002,14,1116,64,1263,47,H,0,57.0,12.56,108.8,96.2,-0.062
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97382,2020,128,1204,81,1209,62,A,0,134.0,3.39,102.2,98.8,0.005
97383,2020,128,1402,85,1111,68,H,0,93.0,7.91,106.3,98.3,-0.050
97384,2020,128,1299,86,1224,77,N,0,287.0,-10.07,92.3,102.4,0.068
97385,2020,128,1393,81,1314,53,N,0,51.0,13.28,112.8,99.6,-0.060
97386,2020,128,1389,56,1233,54,N,0,194.0,-1.98,95.4,97.3,0.023

In [7]:
df_features_season = pd.merge(
    df_features_season,
    pomeroy,
    how='left',
    left_on=['Season', 'LTeamID'],
    right_on=['Season', 'TeamID']
).rename(columns={
    'Rank':'RankL',
    'AdjEM':'AdjEML',
    'AdjO':'AdjOL',
    'AdjD':'AdjDL',
    'Luck':'LuckL',
}).drop('TeamID',axis=1)

In [8]:
df_features_season[df_features_season.isna().any(axis=1)]

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,RankW,AdjEMW,AdjOW,AdjDW,LuckW,RankL,AdjEML,AdjOL,AdjDL,LuckL
28267,2008,4,1338,103,1223,62,H,0,22.0,19.91,116.5,96.6,0.027,NaN,NaN,NaN,NaN,NaN
28335,2008,5,1387,91,1223,56,N,0,157.0,0.95,100.9,100.0,0.067,NaN,NaN,NaN,NaN,NaN
28368,2008,6,1299,96,1223,71,N,0,308.0,-15.38,96.1,111.5,0.091,NaN,NaN,NaN,NaN,NaN
28744,2008,15,1322,105,1223,96,H,0,253.0,-8.60,98.5,107.1,0.090,NaN,NaN,NaN,NaN,NaN
28981,2008,20,1456,79,1223,70,H,0,189.0,-2.99,100.3,103.3,0.053,NaN,NaN,NaN,NaN,NaN
29279,2008,27,1375,66,1223,62,H,0,65.0,11.80,112.6,100.8,-0.002,NaN,NaN,NaN,NaN,NaN
29535,2008,34,1374,90,1223,79,H,0,283.0,-12.04,95.0,107.0,0.054,NaN,NaN,NaN,NaN,NaN
29687,2008,42,1166,110,1223,73,H,0,74.0,10.80,108.7,97.9,0.049,NaN,NaN,NaN,NaN,NaN
30051,2008,54,1223,63,1300,56,A,0,NaN,NaN,NaN,NaN,NaN,334.0,-23.17,85.3,108.5,0.032
31083,2008,78,1410,82,1223,68,H,0,244.0,-7.73,105.5,113.2,-0.005,NaN,NaN,NaN,NaN,NaN
33408,2009,11,1165,79,1377,69,H,0,107.0,5.23,108.5,103.3,-0.005,NaN,NaN,NaN,NaN,NaN
33433,2009,11,1315,61,1282,56,A,0,NaN,NaN,NaN,NaN,NaN,281.0,-10.90,99.4,110.4,-0.003
33518,2009,13,1153,77,1377,46,H,0,86.0,8.72,108.7,100.0,0.032,NaN,NaN,NaN,NaN,NaN
33956,2009,22,1201,79,1370,58,H,0,207.0,-3.78,99.7,103.5,-0.043,NaN,NaN,NaN,NaN,NaN
34045,2009,24,1370,61,1256,46,N,0,NaN,NaN,NaN,NaN,NaN,163.0,-0.00,101.3,101.3,-0.035
34083,2009,25,1361,75,1370,56,N,0,36.0,16.05,109.4,93.3,0.020,NaN,NaN,NaN,NaN,NaN
34171,2009,26,1340,81,1370,67,N,0,118.0,4.04,109.2,105.1,0.025,NaN,NaN,NaN,NaN,NaN
34293,2009,29,1285,83,1315,63,H,0,172.0,-0.70,104.1,104.8,0.030,NaN,NaN,NaN,NaN,NaN
34296,2009,29,1323,102,1377,76,H,0,41.0,15.38,115.0,99.6,-0.034,NaN,NaN,NaN,NaN,NaN
34490,2009,33,1320,69,1315,49,H,0,83.0,9.70,110.6,100.9,0.051,NaN,NaN,NaN,NaN,NaN
34497,2009,33,1340,73,1370,68,H,0,118.0,4.04,109.2,105.1,0.025,NaN,NaN,NaN,NaN,NaN
34752,2009,41,1370,60,1142,59,A,0,NaN,NaN,NaN,NaN,NaN,269.0,-9.52,97.6,107.1,-0.100
34789,2009,43,1370,55,1414,52,A,0,NaN,NaN,NaN,NaN,NaN,217.0,-4.39,104.1,108.5,-0.005
34976,2009,47,1453,96,1315,58,H,0,79.0,10.16,112.9,102.7,-0.018,NaN,NaN,NaN,NaN,NaN
35076,2009,49,1455,66,1315,51,H,0,134.0,2.39,102.8,100.4,-0.004,NaN,NaN,NaN,NaN,NaN
35193,2009,55,1377,74,1309,66,A,0,NaN,NaN,NaN,NaN,NaN,282.0,-11.32,91.8,103.1,0.068
35235,2009,56,1333,59,1370,50,H,0,111.0,4.91,106.1,101.2,0.068,NaN,NaN,NaN,NaN,NaN
35363,2009,59,1370,49,1258,39,H,0,NaN,NaN,NaN,NaN,NaN,323.0,-18.69,89.2,107.9,0.005
35526,2009,62,1339,71,1370,67,H,0,109.0,5.01,107.3,102.3,-0.006,NaN,NaN,NaN,NaN,NaN
35572,2009,63,1401,76,1315,62,H,0,45.0,15.01,113.1,98.1,0.053,NaN,NaN,NaN,NaN,NaN
36449,2009,82,1370,99,1188,82,H,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028
36453,2009,82,1377,98,1315,77,A,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36786,2009,89,1370,71,1188,51,A,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028
36790,2009,89,1377,86,1315,75,H,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37043,2009,96,1188,73,1377,68,H,0,300.0,-13.72,91.2,104.9,0.028,NaN,NaN,NaN,NaN,NaN
37114,2009,96,1370,83,1315,60,H,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37304,2009,101,1294,80,1315,72,H,0,202.0,-3.34,103.3,106.7,-0.075,NaN,NaN,NaN,NaN,NaN
37449,2009,103,1370,73,1377,59,H,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37529,2009,105,1370,78,1167,54,A,0,NaN,NaN,NaN,NaN,NaN,272.0,-9.69,100.1,109.8,0.011
37643,2009,108,1315,76,1188,68,H,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028
37783,2009,110,1377,107,1188,73,H,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028
37864,2009,113,1370,63,1186,59,A,1,NaN,NaN,NaN,NaN,NaN,253.0,-7.74,97.7,105.4,0.051
38001,2009,116,1315,73,1370,68,H,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38098,2009,117,1370,87,1377,85,A,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38154,2009,118,1315,72,1188,68,A,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028
38210,2009,120,1449,87,1370,60,H,0,17.0,22.09,113.1,91.0,-0.005,NaN,NaN,NaN,NaN,NaN
38377,2009,124,1315,68,1377,66,H,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38397,2009,124,1370,78,1188,71,N,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028
38449,2009,125,1370,76,1315,59,A,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38452,2009,125,1377,116,1188,79,N,0,NaN,NaN,NaN,NaN,NaN,300.0,-13.72,91.2,104.9,0.028

In [9]:
df_features_season.fillna(0,inplace=True)

In [10]:
upsets = df_features_season[df_features_season['RankW'] > df_features_season['RankL']].groupby(['Season','WTeamID']).count().reset_index()[['Season','WTeamID','RankW']]

In [11]:
upsets = upsets.rename(columns={'WTeamID':'TeamID','RankW':'Upsets'})

In [12]:
upsets.fillna(0,inplace=True)

In [16]:
upsets.to_csv("Upsets.csv",index=False)

In [14]:
tourney = pd.read_csv('MNCAATourneyCompactResults.csv')

In [15]:
seeds = pd.read_csv("MNCAATourneySeeds.csv")
seeds['Seed'] = seeds['Seed'].apply(lambda x: int(x[1:3]))

tourney = tourney.merge(seeds,how="left",left_on=['Season','WTeamID'],right_on=['Season','TeamID']).rename(columns={'Seed': 'SeedW'})
tourney = tourney.merge(seeds,how="left",left_on=['Season','LTeamID'],right_on=['Season','TeamID']).rename(columns={'Seed': 'SeedL'})

In [138]:
tourney = tourney.merge(upsets,how="left",left_on=['Season','WTeamID'],right_on=['Season','TeamID']).rename(columns={'Upsets': 'UpsetsW'})
tourney = tourney.merge(upsets,how="left",left_on=['Season','LTeamID'],right_on=['Season','TeamID']).rename(columns={'Upsets': 'UpsetsL'})

tourney =  tourney.T.drop_duplicates().T

In [144]:
tourney[(tourney['SeedW'] > tourney['SeedL']) & (tourney['Season']>2014) & (tourney['UpsetsW']>=tourney['Upsets'])].sort_values('UpsetsW',ascending=False)

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,SeedW,SeedL,TeamID_x,UpsetsW,TeamID_y,UpsetsL
2121,2018,136,1104,86,1439,83,N,0,9,8,1104.0,9.0,1439.0,4.0
2189,2019,136,1124,78,1393,69,N,0,9,8,1124.0,7.0,1393.0,3.0
1998,2016,136,1344,70,1425,69,N,0,9,8,1344.0,7.0,1425.0,3.0
2199,2019,136,1278,86,1257,76,N,0,10,7,1278.0,6.0,1257.0,3.0
2142,2018,137,1243,69,1166,59,N,0,9,8,1243.0,6.0,1166.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2212,2019,137,1332,72,1458,54,N,0,12,5,NaN,NaN,1458.0,1.0
2238,2019,143,1403,63,1276,44,N,0,3,2,NaN,NaN,NaN,NaN
2244,2019,145,1403,75,1211,69,N,0,3,1,NaN,NaN,NaN,NaN
2247,2019,146,1277,68,1181,67,N,0,2,1,NaN,NaN,1181.0,2.0
2248,2019,152,1403,61,1277,51,N,0,3,2,NaN,NaN,NaN,NaN